easy_admin:
    site_name: 'Digitale Plattform'
    design:
        form_theme:   'vertical'
        color_scheme: 'dark'
        assets:
            css:
                - '/bundles/app/stylesheets/demo.css'
