easy_admin:
    design:
        menu:
            - label: 'menu.transformations'
              icon: 'exchange'
              children:
                  - { entity: 'Transformation', icon: 'th-list', label: 'menu.transformations.list' }
            - label: 'menu.data'
              icon: 'database'
              children:
                  - { entity: 'Transformation', icon: 'th-list', label: 'menu.data.list' }
                  - { entity: 'Transformation', icon: 'th-list', label: 'menu.data.streams' }
                  - { entity: 'Crawler', icon: 'th-list', label: 'menu.data.sources' }
                  - { entity: 'Transformation', icon: 'th-list', label: 'menu.data.analyse' }
            - label: 'menu.communication'
              icon: 'inbox'
              children:
                  - { entity: 'Community', icon: 'th-list', label: 'menu.communication.communities' }
            - label: 'menu.processes'
              icon: 'tasks'
              children:
                  - { entity: 'Transformation', icon: 'th-list', label: 'menu.processes.list' }
            - label: 'menu.experience'
              icon: 'users'
              children:
                  - { entity: 'Transformation', icon: 'th-list', label: 'menu.experience.list' }
            - label: 'menu.networks'
              icon: 'stack-exchange'
              children:
                  - { entity: 'Transformation', icon: 'th-list', label: 'menu.networks.list' }